image:
  repository: 027089197503.dkr.ecr.eu-west-2.amazonaws.com/lesson7-ecr
  tag: latest
  pullPolicy: IfNotPresent

containerPort: 8000

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

env:
  DJANGO_SETTINGS_MODULE: "myapp.settings"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

ingress:
  enabled: false
  className: nginx
  host: yourdomain.com
  path: /
  pathType: Prefix
  tls: false
  # clusterIssuer: letsencrypt-prod
image:
  repository: 027089197503.dkr.ecr.eu-west-2.amazonaws.com/lesson7-ecr
  tag: latest
  pullPolicy: IfNotPresent

containerPort: 8000

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

env:
  DJANGO_SETTINGS_MODULE: "myapp.settings"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

ingress:
  enabled: false
  className: nginx
  host: yourdomain.com
  path: /
  pathType: Prefix
  tls: false
  # clusterIssuer: letsencrypt-prod
